apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-postgres
  namespace: saga-pattern
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "${WORKLOAD_IDENTITY_CLIENT_ID}"
    keyvaultName: "${KEY_VAULT_NAME}"
    tenantId: "${TENANT_ID}"
    objects: |
      array:
        - |
          objectName: saga-postgres-username
          objectType: secret
          objectAlias: username
        - |
          objectName: saga-postgres-password
          objectType: secret
          objectAlias: password
    objectsFormat: yaml
  secretObjects:
  - secretKey: username
    path: username
    objectName: username
  - secretKey: password
    path: password
    objectName: password
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-rabbitmq
  namespace: saga-pattern
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "${WORKLOAD_IDENTITY_CLIENT_ID}"
    keyvaultName: "${KEY_VAULT_NAME}"
    tenantId: "${TENANT_ID}"
    objects: |
      array:
        - |
          objectName: saga-rabbitmq-username
          objectType: secret
          objectAlias: username
        - |
          objectName: saga-rabbitmq-password
          objectType: secret
          objectAlias: password
    objectsFormat: yaml
  secretObjects:
  - secretKey: username
    path: username
    objectName: username
  - secretKey: password
    path: password
    objectName: password
